const kurlyDB = [
    {
        src:'./images/kurly_001.jpg',
        name:'[해태] 여름 시즌 한정 트로피컬 에디션 간식 4종 (택1)',
        summary:'새콤달콤한 여름맛 간식',
        price:3580,
        sale:7,
        review:154,
    },
    {
        src:'./images/kurly_002.jpg',
        name:'[피자로빈슨] 뉴욕 메가 슬라이스 피자 페퍼로니',
        summary:'짭쪼름한 페퍼로니가 듬뿍',
        price:5500,
        sale:20,
        review:18,
    },
    {
        src:'./images/kurly_003.jpg',
        name:'[비비고] 왕교자 1.05kg',
        summary:'속이 꽉 찬 만두의 정석',
        price:9980,
        sale:15,
        review:243,
    },
    {
        src:'./images/kurly_004.jpg',
        name:'[서울우유] 초코 우유 300ml',
        summary:'달콤한 초코의 진한 맛',
        price:1300,
        sale:10,
        review:87,
    },
    {
        src:'./images/kurly_005.jpg',
        name:'[오뚜기] 진라면 매운맛 5입',
        summary:'매콤한 국물의 유혹',
        price:3780,
        sale:5,
        review:321,
    },
    {
        src:'./images/kurly_006.jpg',
        name:'[풀무원] 생가득 물만두 800g',
        summary:'쫄깃한 피와 담백한 속',
        price:6980,
        sale:12,
        review:198,
    },
    {
        src:'./images/kurly_007.jpg',
        name:'[롯데] 꼬깔콘 고소한맛 72g',
        summary:'바삭하고 고소한 콘스낵',
        price:1200,
        sale:8,
        review:59,
    },
    {
        src:'./images/kurly_008.jpg',
        name:'[청정원] 안주야 직화 불막창 180g',
        summary:'불맛 가득한 막창',
        price:8480,
        sale:18,
        review:134,
    },
    {
        src:'./images/kurly_009.jpg',
        name:'[빙그레] 바나나맛 우유 240ml',
        summary:'추억의 국민 음료',
        price:1500,
        sale:5,
        review:412,
    },
    {
        src:'./images/kurly_010.jpg',
        name:'[사조] 참치 마일드 150g',
        summary:'고소하고 담백한 참치',
        price:2180,
        sale:10,
        review:203,
    },
    {
        src:'./images/kurly_011.jpg',
        name:'[남양] 맛있는 우유 GT 900ml',
        summary:'신선한 1A 등급 우유',
        price:2500,
        sale:7,
        review:145,
    },
    {
        src:'./images/kurly_012.jpg',
        name:'[매일] 요거트 떠먹는 플레인 85g 4입',
        summary:'부드럽고 건강한 맛',
        price:2980,
        sale:6,
        review:92,
    }
];
